
File: D:\github\KSP-1-Mods\DeepFreeze\Source\..\DeepFreezeContinued.version, semicolon missing
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("1.0.0.0")]
 [assembly: AssemblyFileVersion("1.0.0.0")]
